### ISSUE TITLE
Suggestion: Change body text color

### ISSUE THREAD

**Issue by Tola200** [Tola200010/github-crash-course#1]
I think it look better if the main body color a bit more red
This styling rule could be changed like this:
```css
body {
  margin: 0;
  text-align: center;
  background-color: #322e2d;
  color: #89c20c;
}
```
